# Generated by Django 3.1.4 on 2021-01-25 23:31

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='casa_paz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('lider', models.CharField(max_length=150, verbose_name='Lider')),
                ('direccion', models.CharField(max_length=300, verbose_name='Direccion')),
                ('telefono', models.CharField(blank=True, max_length=300, null=True, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'Casa de Paz',
                'verbose_name_plural': 'Casas de Paz',
                'db_table': 'casa_paz',
            },
        ),
        migrations.CreateModel(
            name='concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo Concepto')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'concepto',
            },
        ),
        migrations.CreateModel(
            name='excercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('description', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('img', models.CharField(max_length=150, verbose_name='Imagen')),
                ('leftColor', models.CharField(max_length=150, verbose_name='leftColor')),
                ('rightColor', models.CharField(max_length=150, verbose_name='rightColor')),
            ],
        ),
        migrations.CreateModel(
            name='red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('mentor', models.CharField(max_length=150, verbose_name='Mentor')),
                ('secretario', models.CharField(max_length=150, unique=True, verbose_name='Secretario')),
            ],
            options={
                'verbose_name': 'Red',
                'verbose_name_plural': 'Redes',
                'db_table': 'Red',
            },
        ),
        migrations.CreateModel(
            name='tesoreria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tesoreria',
                'verbose_name_plural': 'Tesorerias',
                'db_table': 'tesoreria',
            },
        ),
        migrations.CreateModel(
            name='rep_casa_paz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asist_total', models.PositiveIntegerField(verbose_name='Asistencia')),
                ('cant_visita', models.PositiveIntegerField(verbose_name='Visitas')),
                ('cant_nc', models.PositiveIntegerField(verbose_name='Nuevos Convertidos')),
                ('cant_bajas', models.PositiveIntegerField(verbose_name='Bajas')),
                ('ofrendas', models.FloatField(verbose_name='Ofrendas')),
                ('casa_paz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.casa_paz')),
            ],
            options={
                'verbose_name': 'Diezmo',
                'verbose_name_plural': 'Diezmos',
                'db_table': 'diezmos',
            },
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Movimiento')),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('concepto', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='core.concepto', verbose_name='Concepto')),
                ('tesoreria', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tesoreria', verbose_name='Tesoreria')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
            },
        ),
        migrations.CreateModel(
            name='membresia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('Exp', models.PositiveIntegerField(verbose_name='Expediente')),
                ('estado_membresia', models.CharField(max_length=50, verbose_name='Estado del Miembro')),
                ('ci', models.CharField(blank=True, max_length=11, null=True, verbose_name='Carne de Identidad')),
                ('nombres', models.CharField(max_length=150, verbose_name='Nombres')),
                ('apellido1', models.CharField(max_length=150, verbose_name='Primer Apellido')),
                ('apellido2', models.CharField(max_length=150, verbose_name='Segundo Apellido')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Civil')),
                ('telf_fijo', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefono Fijo')),
                ('telf_celular', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefono Celular')),
                ('telf_cercano', models.CharField(blank=True, max_length=60, null=True, verbose_name='Telefono Cercano')),
                ('correo_electronico', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electronico')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupacion')),
                ('centro_lab', models.CharField(blank=True, max_length=100, null=True, verbose_name='Centro de Trabajo o Estudio')),
                ('fecha_conversion', models.DateField(blank=True, null=True, verbose_name='Fecha de Conversion')),
                ('fecha_bautismo', models.DateField(blank=True, null=True, verbose_name='Fecha de Bautismo')),
                ('bautismo_ES', models.BooleanField(blank=True, null=True, verbose_name='Bautismo Espiritu Santo')),
                ('cargo_iglesia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo en la Iglesia')),
                ('casa_paz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='core.casa_paz')),
                ('mentor_asig', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.NOT_PROVIDED, to='core.membresia')),
            ],
            options={
                'verbose_name': 'Miembros',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembros',
            },
        ),
        migrations.CreateModel(
            name='diezmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('importe', models.FloatField(verbose_name='Importe')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='core.membresia')),
            ],
        ),
        migrations.AddField(
            model_name='casa_paz',
            name='red',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.red'),
        ),
    ]
