# Generated by Django 3.1.4 on 2021-01-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=8000, null=True, verbose_name='image'),
        ),
    ]
