# Generated by Django 3.1.4 on 2021-01-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210125_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
